"use client";

import {useEffect,useState} from "react";
import {ArrowRight,AtSign,Mail,MapPin,Package,Phone,ShoppingBag} from "lucide-react";
import {createSupabaseBrowserClient} from "../../lib/supabase";

type Product={id:string;name:string;description:string|null;category:string;price:number;image_url:string|null};
const money=(value:number)=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED"}).format(value);

export default function StorePage(){
 const[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;async function load(){try{const supabase=createSupabaseBrowserClient(),{data,error:queryError}=await supabase.from("storefront_products").select("id,name,description,category,price,image_url").eq("active",true).order("created_at",{ascending:false});if(!active)return;if(queryError)throw queryError;setProducts((data||[]) as Product[])}catch{if(active)setError("The collection is being updated. Please contact Giftique for current availability.")}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[]);
 return <main className="public-store"><header className="public-nav"><a className="public-brand" href="#home"><span>G</span><strong>GIFTIQUE ATELIER</strong></a><nav><a href="#home">Home</a><a href="#products">Products</a><a href="#contact">Contact</a><a className="public-bag" href="#products" aria-label="View products"><ShoppingBag size={18}/></a></nav></header><section className="public-hero" id="home"><div><span>CURATED GIFTING FROM THE UAE</span><h1>Small details.<br/>Beautiful memories.</h1><p>Thoughtful gifts, bridal details, and keepsakes made for the moments you want to remember.</p><a className="public-cta" href="#products">Shop the collection <ArrowRight size={16}/></a></div><div className="hero-note"><span>GIFTIQUE</span><strong>Made for<br/>your moment.</strong></div></section><section className="public-intro"><span>THE GIFTIQUE EDIT</span><h2>Find a piece that feels personal.</h2><p>Explore our current collection of celebration pieces, thoughtful keepsakes, and gift details for brides, friends, and the people you love.</p></section><section className="public-products" id="products"><div className="public-section-head"><div><span>SHOP THE COLLECTION</span><h2>Made to be remembered.</h2></div><Package size={24}/></div>{loading?<p className="public-empty">Loading products…</p>:error?<p className="public-empty">{error}</p>:!products.length?<p className="public-empty">Products will appear here shortly.</p>:<div className="public-product-grid">{products.map(product=><article className="public-product" key={product.id}>{product.image_url?<img src={product.image_url} alt={product.name}/>:<div className="public-product-image"><Package size={28}/></div>}<div><small>{product.category}</small><h3>{product.name}</h3>{product.description&&<p>{product.description}</p>}<strong>{money(product.price)}</strong></div></article>)}</div>}</section><section className="public-contact" id="contact"><div><span>LET'S CONNECT</span><h2>Have a gifting question?</h2><p>Reach out for product details, custom requests, and order support.</p></div><div className="contact-links"><a href="mailto:hello@giftiqueatelier.com"><Mail size={17}/>hello@giftiqueatelier.com</a><a href="tel:+971000000000"><Phone size={17}/>Contact Giftique</a><a href="https://www.instagram.com/giftiqueatelier/" target="_blank" rel="noreferrer"><AtSign size={17}/>Instagram</a><span><MapPin size={17}/>United Arab Emirates</span></div></section><footer className="public-footer"><strong>GIFTIQUE ATELIER</strong><span>Thoughtful gifting, beautifully considered.</span><a href="./">Team login</a></footer></main>;
}
