"use client";
import {useState} from "react";
import {ArrowLeft,Check,ShieldCheck} from "lucide-react";

export default function AutomationPage(){
 const[sent,setSent]=useState(false);
 function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();
  const d=new FormData(e.currentTarget);
  const lead={name:String(d.get("name")),email:String(d.get("email")),business:String(d.get("business")),createdAt:new Date().toISOString()};
  const old=JSON.parse(localStorage.getItem("ezdevsoft-leads")||"[]");
  localStorage.setItem("ezdevsoft-leads",JSON.stringify([...old,lead]));
  const subject=encodeURIComponent(`Automation enquiry from ${lead.name}`);
  const body=encodeURIComponent(`Name: ${lead.name}\nEmail: ${lead.email}\nBusiness: ${lead.business}\n\nI would like a free TikTok and Instagram automation example for my business.`);
  setSent(true);
  window.location.href=`mailto:ezhrmovv@ezdevsoft.net?subject=${subject}&body=${body}`;
 }
 return <main className="auto-page"><nav className="auto-nav"><a href="/"><ArrowLeft size={17}/>Back to Giftique Ledger</a><a href="https://ezdevsoft.net/" target="_blank" rel="noreferrer">EZDEVSOFT</a></nav><section className="auto-hero"><div className="auto-copy"><span>TIKTOK + INSTAGRAM AUTOMATION</span><h1>Turn social attention into organized sales leads.</h1><p>An automation engine built for online sellers. It captures enquiries, replies faster, organizes interested shoppers and reminds your team who needs follow-up.</p><div className="auto-benefits"><span><Check/>Capture enquiries automatically</span><span><Check/>Qualify interested shoppers</span><span><Check/>Follow up without spreadsheets</span><span><Check/>See which content creates leads</span></div></div><LeadForm sent={sent} submit={submit}/></section><section className="how"><div className="how-title"><span>A SIMPLE EXAMPLE</span><h2>From “How much?” to a sales opportunity</h2></div><div className="how-grid"><article><b>01</b><h3>A shopper reacts</h3><p>They comment on your TikTok or send a product enquiry through Instagram.</p></article><article><b>02</b><h3>The engine responds</h3><p>It shares the right details, asks useful questions and captures their email.</p></article><article><b>03</b><h3>Your team receives a lead</h3><p>The enquiry arrives organized, with the product and conversation context.</p></article><article><b>04</b><h3>Follow-up gets done</h3><p>Reminders help your sales team close warm leads before they disappear.</p></article></div></section><section className="examples"><span>BUILT FOR ONLINE SELLERS</span><h2>What this could look like</h2><div><article><b>Fashion boutique</b><p>Someone comments “size?” → receives options → shares their email → sales staff follows up.</p></article><article><b>Beauty store</b><p>A skincare enquiry is qualified by concern and budget before it reaches the team.</p></article><article><b>Gift business</b><p>An event-date enquiry triggers product suggestions and a reminder before the buying deadline.</p></article></div></section><footer className="auto-footer">Automation by <a href="https://ezdevsoft.net/" target="_blank" rel="noreferrer">ezdevsoft.net</a> · <a href="mailto:ezhrmovv@ezdevsoft.net">ezhrmovv@ezdevsoft.net</a></footer></main>
}

function LeadForm({sent,submit}:any){return <form className="auto-form" onSubmit={submit}>{sent?<div className="auto-success"><ShieldCheck/><h2>Your email is ready.</h2><p>Please press Send in your email app so the request reaches ezhrmovv@ezdevsoft.net.</p><a href="mailto:ezhrmovv@ezdevsoft.net">Email ezhrmovv@ezdevsoft.net</a></div>:<><small>FREE AUTOMATION REVIEW</small><h2>Get an example for your business</h2><p>Tell us what you sell and we’ll prepare a simple automation opportunity.</p><label>Name<input name="name" required placeholder="Your name"/></label><label>Business<select name="business" required defaultValue=""><option value="" disabled>Select business type</option><option>Fashion & accessories</option><option>Beauty & skincare</option><option>Gifts & events</option><option>Food & beverage</option><option>Other online business</option></select></label><label>Email address<input name="email" type="email" required placeholder="you@business.com"/></label><button type="submit">Email my request</button><em>This opens a pre-filled email addressed to ezhrmovv@ezdevsoft.net.</em></>}</form>}
