"use client";

import { useCallback, useEffect, useId, useRef, useState, type FormEvent, type ReactNode } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";
import { accountingReports, type AccountingReport, type AccountingReportId } from "@/lib/management-catalog";
import type { BusinessForm, BusinessRecord, Capabilities, Field, Values } from "@/lib/business-types";

const button = "rounded-lg border border-[#ded5ca] bg-white px-4 py-2 text-sm font-medium hover:bg-[#f5efe7] disabled:opacity-50";
const primary = `${button} !bg-[#725839] !text-white hover:!bg-[#59442c]`;
const input = "w-full rounded-lg border border-[#d9d1c7] bg-white px-3 py-2 text-sm disabled:bg-[#f4f1ed]";
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: unknown, currency = "AED") => new Intl.NumberFormat("en-AE", { style: "currency", currency }).format(Number(value || 0));
const display = (value: unknown) => value == null ? "—" : typeof value === "object" ? "" : String(value);
type Api = <T>(query: Record<string, string>, body?: Record<string, unknown>) => Promise<T>;

export default function ManagementWorkspace({ children }: { children: ReactNode }) {
  const [supabase] = useState(createSupabaseBrowserClient);
  const [owner, setOwner] = useState(false);
  const [tab, setTab] = useState("Operations");
  const [caps, setCaps] = useState<Capabilities | null>(null);
  const [error, setError] = useState("");
  const api = useCallback(async <T,>(query: Record<string, string>, body?: Record<string, unknown>): Promise<T> => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) throw new Error("Sign in again to continue.");
    const response = await fetch(`/api/proxc-management/business?${new URLSearchParams(query)}`, {
      method: body ? "POST" : "GET", headers: { Authorization: `Bearer ${session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined, cache: "no-store",
    });
    const data = await response.json() as T & { error?: string };
    if (!response.ok) throw new Error(data.error || "Request unavailable.");
    return data;
  }, [supabase]);
  const load = useCallback(async () => { setError(""); try { setCaps(await api<Capabilities>({ action: "capabilities" })); } catch (e) { setError(e instanceof Error ? e.message : "Setup unavailable."); } }, [api]);
  useEffect(() => { let active = true; void supabase.auth.getSession().then(({ data }) => { if (active) setOwner(data.session?.user.app_metadata?.role === "owner"); }); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { setOwner(session?.user.app_metadata?.role === "owner"); setCaps(null); setTab("Operations"); }); return () => { active = false; subscription.unsubscribe(); }; }, [supabase]);
  useEffect(() => { if (owner) { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); } }, [owner, load]);
  const tabs = owner ? ["Operations", "Accounting", "Cash & Banks", "Credit & Bills", "Staff", "Payroll", "Company & Documents"] : ["Operations"];
  return <>
    <nav aria-label="Management sections" className="mb-6 flex flex-wrap gap-2">{tabs.map(item => <button key={item} type="button" aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)} className={tab === item ? primary : button}>{item}</button>)}</nav>
    {tab === "Operations" ? children : <section className="rounded-2xl border border-[#e5dfd8] bg-white p-5 sm:p-7" aria-label={tab}>
      <h2 className="text-2xl font-semibold">{tab}</h2><p className="mb-6 mt-2 text-sm text-[#716b66]">Giftique · Owner access · Records saved in ERPNext</p>
      {error ? <><p role="alert" className="text-red-800">{error}</p><button className={button} onClick={() => void load()}>Retry connection</button></> : !caps ? <p role="status">Loading business setup…</p> : <>
        {tab === "Accounting" && <><Reports supabase={supabase} /><RecordArea api={api} caps={caps} kinds={["journals", "accounts"]} /></>}
        {tab === "Cash & Banks" && <><Payments api={api} /><RecordArea api={api} caps={caps} kinds={["payments", "bank_accounts", "banks"]} /></>}
        {tab === "Credit & Bills" && <><p className="mb-4 text-sm">Track supplier bills and customer credit notes. Receivables and payables ageing are available in Accounting.</p><CreditNote api={api} /><RecordArea api={api} caps={caps} kinds={["purchase_invoices", "suppliers", "customers"]} /></>}
        {tab === "Staff" && <><p className="mb-4 text-sm">Employee records are private to the owner. Adding an employee does not create a website login.</p><RecordArea api={api} caps={caps} kinds={["employees", "departments", "designations", "holiday_lists", "holiday_assignments"]} /></>}
        {tab === "Payroll" && (caps.payroll ? <><p className="mb-4 text-sm leading-6">Set up employees, holiday lists, and submitted holiday assignments in Staff. Create salary components and structures, then assign a structure to each employee. Save a payroll run, submit it to create draft salary slips, review those slips, and submit payroll to post the accrual. Salary bank transfers are performed separately.</p><RecordArea api={api} caps={caps} kinds={["payroll_runs", "salary_slips", "salary_assignments", "salary_structures", "salary_components"]} /></> : <p role="alert">Payroll requires the HRMS installation to be completed.</p>)}
        {tab === "Company & Documents" && <Documents api={api} caps={caps} onChanged={load} supabase={supabase} />}
      </>}
    </section>}
  </>;
}

function Reports({ supabase }: { supabase: ReturnType<typeof createSupabaseBrowserClient> }) {
  const [reportId, setReportId] = useState<AccountingReportId>("profit_loss");
  const [from, setFrom] = useState(`${today().slice(0, 4)}-01-01`), [to, setTo] = useState(today);
  const [report, setReport] = useState<AccountingReport | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function run(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setReport(null); try { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(`/api/proxc-management/reports?${new URLSearchParams({ report: reportId, from, to })}`, { headers: { Authorization: `Bearer ${session?.access_token}` }, cache: "no-store" }); const result = await response.json() as { report: AccountingReport; error?: string }; if (!response.ok) throw new Error(result.error); setReport(result.report); } catch (e) { setError(e instanceof Error ? e.message : "Report unavailable."); } finally { setBusy(false); } }
  return <div className="mb-8">
    <form onSubmit={run} className="flex flex-wrap items-end gap-3"><label className="grow text-sm">Report<select className={input} value={reportId} onChange={e => { setReportId(e.target.value as AccountingReportId); setReport(null); }}>{Object.entries(accountingReports).map(([id, item]) => <option value={id} key={id}>{item.title}</option>)}</select></label><label className="text-sm">From<input type="date" className={input} required value={from} onChange={e => { setFrom(e.target.value); setReport(null); }} /></label><label className="text-sm">To / as of<input type="date" className={input} required value={to} onChange={e => { setTo(e.target.value); setReport(null); }} /></label><button className={primary} disabled={busy}>{busy ? "Loading…" : "Run report"}</button></form>
    <p className="my-3 text-sm text-[#716b66]">{accountingReports[reportId].description}</p>
    {error && <p role="alert" className="text-red-800">{error}</p>}
    {report && <><h3 className="mb-3 font-semibold">{report.title} · {report.company}</h3><div className="mb-4 flex flex-wrap gap-3">{report.summary.map((item, i) => <div key={i} className="rounded-lg bg-[#f7f3ed] p-3"><p className="text-sm">{item.label}</p><strong>{item.datatype === "Currency" ? money(item.value, item.currency || report.currency) : display(item.value)}</strong></div>)}</div><div className="max-h-[550px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-[#f3eee7]"><tr>{report.columns.map((col, i) => <th className="whitespace-nowrap p-3" key={`${col.fieldname}-${i}`}>{col.label}</th>)}</tr></thead><tbody>{report.rows.map((row, i) => <tr key={i} className="border-b border-[#eee8e0]">{report.columns.map((col, j) => <td className="min-w-28 p-3" key={`${col.fieldname}-${j}`}>{col.fieldtype === "Currency" && row[col.fieldname] != null ? money(row[col.fieldname], report.currency) : display(row[col.fieldname])}</td>)}</tr>)}</tbody></table>{!report.rows.length && <p className="p-4">No posted records for this report period.</p>}</div></>}
  </div>;
}

function RecordArea({ api, caps, kinds }: { api: Api; caps: Capabilities; kinds: string[] }) {
  const forms = kinds.map(kind => caps.forms.find(f => f.id === kind)).filter((f): f is BusinessForm => !!f);
  const [kind, setKind] = useState(kinds[0]);
  const form = forms.find(f => f.id === kind);
  return <div className="mt-6 border-t border-[#e5dfd8] pt-6"><div className="mb-5 flex flex-wrap gap-2">{forms.map(f => <button key={f.id} className={f.id === kind ? primary : button} onClick={() => setKind(f.id)}>{f.doctype}</button>)}</div>{form && <Records key={kind} form={form} api={api} />}</div>;
}
function initialValues(fields: Field[]): Values {
  return Object.fromEntries(fields.map(field => [field.name, field.type === "Table" ? [] : field.default === "Today" ? today() : ["Check", "Int", "Float", "Currency", "Percent"].includes(field.type) ? Number(field.default || 0) : field.default && !field.default.startsWith(":") ? field.default : ""]));
}
function Records({ form, api }: { form: BusinessForm; api: Api }) {
  const [rows, setRows] = useState<BusinessRecord[]>([]), [hasMore, setHasMore] = useState(false), [page, setPage] = useState(0), [search, setSearch] = useState(""), [filter, setFilter] = useState("");
  const [record, setRecord] = useState<BusinessRecord | null>(null), [editing, setEditing] = useState(false), [values, setValues] = useState<Values>({}), [recordName, setRecordName] = useState("");
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const requestId = useRef(""); const sequence = useRef(0); const panel = useRef<HTMLDivElement>(null);
  const refresh = useCallback(async () => { const id = ++sequence.current; setLoading(true); try { const data = await api<{ records: BusinessRecord[]; hasMore: boolean }>({ action: "records", kind: form.id, page: String(page), search: filter }); if (id === sequence.current) { setRows(data.records); setHasMore(data.hasMore); } } catch (e) { if (id === sequence.current) setError(e instanceof Error ? e.message : "Records unavailable."); } finally { if (id === sequence.current) setLoading(false); } }, [api, form.id, page, filter]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => { clearTimeout(timer); }; }, [refresh]);
  function focus() { requestAnimationFrame(() => { panel.current?.focus(); panel.current?.scrollIntoView({ block: "start", behavior: "smooth" }); }); }
  function apply(doc: BusinessRecord) { setRecord(doc); setValues(Object.fromEntries(form.fields.map(f => [f.name, doc[f.name] ?? (f.type === "Table" ? [] : "")]))); setRecordName(doc.name); setEditing(true); focus(); }
  async function open(name: string) { setBusy(true); setError(""); setNotice(""); try { apply(await api<BusinessRecord>({ action: "record", kind: form.id, name })); requestId.current = crypto.randomUUID(); } catch (e) { setError(e instanceof Error ? e.message : "Record unavailable."); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const doc = await api<BusinessRecord>({}, { action: "save_record", kind: form.id, data: values, request_id: requestId.current, ...(record ? { name: record.name, expected_modified: record.modified } : {}), ...(form.nameRequired ? { record_name: recordName } : {}) }); apply(doc); setNotice(`${doc.name} saved${form.submittable ? " as a draft" : ""}.`); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Save failed."); } finally { setBusy(false); } }
  async function submit(payroll = false, retry = false) { if (!record || !window.confirm(payroll ? "Submit all reviewed salary slips and post the payroll accrual?" : `Submit ${record.name}? This may create accounting entries. Submitted records cannot be edited here.`)) return; setBusy(true); setError(""); setNotice(""); try { const doc = await api<BusinessRecord>({}, { action: retry ? "retry_payroll_slips" : payroll ? "submit_payroll_slips" : "submit_record", ...(!payroll && !retry ? { kind: form.id } : {}), name: record.name, expected_modified: record.modified }); apply(doc); setNotice(payroll ? "Payroll submission requested. Refresh to check completion." : `${doc.name} submitted.`); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Submission failed."); } finally { setBusy(false); } }
  const readonly = !!record && record.docstatus !== 0;
  return <>
    <div className="mb-4 flex flex-wrap justify-between gap-3"><h3 className="text-lg font-semibold">{form.doctype} records</h3><div className="flex gap-2"><button className={button} disabled={busy || loading} onClick={() => { setError(""); void refresh(); }}>Refresh</button>{form.canCreate && <button className={primary} disabled={busy} onClick={() => { setRecord(null); setValues(initialValues(form.fields)); setRecordName(""); requestId.current = crypto.randomUUID(); setEditing(true); setError(""); setNotice(""); focus(); }}>New {form.doctype}</button>}</div></div>
    <form className="mb-4 flex gap-2" onSubmit={e => { e.preventDefault(); setPage(0); setFilter(search); }}><input aria-label={`Search ${form.doctype}`} className={input} value={search} maxLength={80} onChange={e => setSearch(e.target.value)} placeholder="Search records" /><button className={button}>Search</button></form>
    {error && <p role="alert" className="my-3 rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{notice && <p role="status" className="my-3 rounded-lg bg-green-50 p-3 text-green-900">{notice}</p>}
    {loading ? <p role="status">Loading records…</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f7f3ed]"><tr><th className="p-3">Record</th>{form.columns.map(f => <th className="p-3" key={f.name}>{f.label}</th>)}<th className="p-3">State</th></tr></thead><tbody>{rows.map(row => <tr key={row.name} className="border-b border-[#eee8e0]"><td className="p-3"><button disabled={busy} className="font-semibold text-[#725839] underline" onClick={() => void open(row.name)}>{row.name}</button></td>{form.columns.map(f => <td className="p-3" key={f.name}>{f.type === "Currency" ? money(row[f.name]) : display(row[f.name])}</td>)}<td className="p-3">{form.submittable ? ["Draft", "Submitted", "Cancelled"][row.docstatus] : "Saved"}</td></tr>)}</tbody></table>{!rows.length && <p className="p-4">No {form.doctype.toLowerCase()} records found.</p>}</div>}
    <div className="my-4 flex items-center gap-3"><button className={button} disabled={!page || loading} onClick={() => setPage(p => p - 1)}>Previous</button><span className="text-sm">Page {page + 1}</span><button className={button} disabled={!hasMore || loading} onClick={() => setPage(p => p + 1)}>Next</button></div>
    {editing && <div ref={panel} tabIndex={-1} className="mt-6 scroll-mt-6 rounded-xl border border-[#ded5ca] bg-[#fbf9f6] p-5"><div className="mb-4 flex justify-between gap-3"><h4 className="text-lg font-semibold">{record ? record.name : `New ${form.doctype}`}</h4><button className={button} disabled={busy} onClick={() => setEditing(false)}>Close</button></div>
      <form onSubmit={save}><fieldset disabled={busy || readonly}><div className="grid gap-4 sm:grid-cols-2">{form.nameRequired && <label className="text-sm">Record name<input className={input} required disabled={!!record} value={recordName} onChange={e => setRecordName(e.target.value)} /></label>}{form.fields.map(f => <FieldInput key={f.name} field={f} kind={form.id} api={api} value={values[f.name]} onChange={v => setValues(old => ({ ...old, [f.name]: v }))} />)}</div></fieldset>
      {record && <div className="my-4 flex flex-wrap gap-4 text-sm">{["grand_total", "outstanding_amount", "gross_pay", "total_deduction", "net_pay", "total_debit", "total_credit"].filter(k => record[k] != null).map(k => <p key={k}>{k.replaceAll("_", " ")}: <strong>{money(record[k])}</strong></p>)}</div>}
      {form.id === "salary_slips" && record && <div className="my-4 grid gap-3 sm:grid-cols-2">{["earnings", "deductions"].map(key => <div key={key}><strong className="capitalize">{key}</strong>{Array.isArray(record[key]) && record[key].map((row, i) => <p key={i} className="text-sm">{display(row.salary_component)}: {money(row.amount)}</p>)}</div>)}</div>}
      {form.id === "payroll_runs" && record && <div className="my-4"><strong>Included employees</strong>{record.error_message && <p role="alert" className="my-3 text-red-800">{display(record.error_message)}</p>}{Array.isArray(record.employees) && record.employees.map((row, i) => <p key={i} className="text-sm">{display(row.employee_name)} · {display(row.employee)}</p>)}</div>}
      <div className="mt-5 flex flex-wrap gap-3">{!readonly && <button className={primary} disabled={busy}>{busy ? "Working…" : form.submittable ? "Save draft" : "Save record"}</button>}{record && form.submittable && record.docstatus === 0 && <button type="button" className={button} disabled={busy || JSON.stringify(values) !== JSON.stringify(Object.fromEntries(form.fields.map(f => [f.name, record[f.name] ?? (f.type === "Table" ? [] : "")])))} onClick={() => void submit()}>Submit saved draft</button>}{record && form.id === "payroll_runs" && record.docstatus === 1 && !record.salary_slips_created && <button type="button" className={button} disabled={busy} onClick={() => void submit(false, true)}>Retry salary slip creation</button>}{record && form.id === "payroll_runs" && record.docstatus === 1 && !record.salary_slips_submitted && <button type="button" className={primary} disabled={busy || !record.salary_slips_created} onClick={() => void submit(true)}>Submit reviewed salary slips</button>}{record && <button type="button" disabled={busy} className={button} onClick={() => void open(record.name)}>Reload record</button>}</div></form>
    </div>}
  </>;
}

function FieldInput({ field, value, onChange, kind, api, table }: { field: Field; value: Values[string] | undefined; onChange: (value: Values[string]) => void; kind: string; api: Api; table?: string }) {
  const id = useId(); const [choices, setChoices] = useState<{ value: string; label: string }[]>([]); const [error, setError] = useState(""); const seq = useRef(0);
  async function lookup(search = "") { const n = ++seq.current; try { const result = await api<{ value: string; label: string }[]>({ action: "choices", kind, field: field.name, search, ...(table ? { table } : {}) }); if (n === seq.current) { setChoices(result); setError(""); } } catch { if (n === seq.current) setError("Could not load suggestions. Enter an existing record name or retry."); } }
  if (field.type === "Table") { const rows = Array.isArray(value) ? value : []; return <fieldset className="col-span-full rounded-lg border border-[#e5dfd8] p-3"><legend className="px-1 text-sm font-semibold">{field.label}</legend>{rows.map((row, i) => <div key={i} className="mb-3 grid gap-3 rounded-lg bg-white p-3 sm:grid-cols-3">{field.fields?.map(child => <FieldInput key={child.name} field={child} value={row[child.name]} onChange={v => onChange(rows.map((item, n) => n === i ? { ...item, [child.name]: v } : item))} kind={kind} api={api} table={field.name} />)}<button type="button" className={button} onClick={() => onChange(rows.filter((_r, n) => n !== i))}>Remove row {i + 1}</button></div>)}<button type="button" disabled={rows.length >= 100} className={button} onClick={() => onChange([...rows, initialValues(field.fields || [])])}>Add {field.label.toLowerCase()} row</button></fieldset>; }
  if (field.type === "Check") return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!Number(value)} onChange={e => onChange(e.target.checked ? 1 : 0)} />{field.label}</label>;
  const numeric = ["Currency", "Float", "Int", "Percent"].includes(field.type);
  return <label className="text-sm" htmlFor={id}>{field.label}{field.required ? " *" : ""}
    {field.type === "Select" ? <select id={id} className={input} value={display(value === undefined || value === null ? "" : value)} required={field.required} onChange={e => onChange(e.target.value)}><option value="">Select…</option>{field.options?.filter(Boolean).map(option => <option key={option}>{option}</option>)}</select> : ["Text", "Small Text", "Text Editor", "Long Text", "Code"].includes(field.type) ? <textarea id={id} className={input} value={String(value || "")} required={field.required} maxLength={2000} onChange={e => onChange(e.target.value)} /> : <input id={id} className={input} value={String(value ?? "")} required={field.required} type={field.type === "Date" ? "date" : numeric ? "number" : "text"} step={numeric ? "any" : undefined} list={field.type === "Link" ? `${id}-choices` : undefined} onFocus={() => { if (field.type === "Link") void lookup(); }} onChange={e => { onChange(numeric ? (e.target.value === "" ? "" : Number(e.target.value)) : e.target.value); }} onBlur={e => { if (field.type === "Link" && e.target.value) void lookup(e.target.value); }} />}
    {field.type === "Link" && <datalist id={`${id}-choices`}>{choices.map(choice => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</datalist>}{error && <small role="status" className="text-amber-800">{error}</small>}
  </label>;
}

type BankBalance = { name: string; account_name: string; account_type: string; account_currency: string; balance: number };
type InvoiceChoice = { name: string; customer_name?: string; supplier_name?: string; outstanding_amount: number; currency: string; modified: string };
function Payments({ api }: { api: Api }) {
  const [reference, setReference] = useState(""), [referenceDate, setReferenceDate] = useState(today);
  const [date, setDate] = useState(today), [banks, setBanks] = useState<BankBalance[]>([]), [invoices, setInvoices] = useState<InvoiceChoice[]>([]), [direction, setDirection] = useState("Receive"), [invoice, setInvoice] = useState(""), [account, setAccount] = useState(""), [amount, setAmount] = useState(0), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const requestId = useRef("");
  const load = useCallback(async () => { setBusy(true); setError(""); try { const [b, i] = await Promise.all([api<BankBalance[]>({ action: "bank_balances", date }), api<InvoiceChoice[]>({ action: "invoice_choices", direction })]); setBanks(b); setInvoices(i); setInvoice(""); setAmount(0); } catch (e) { setError(e instanceof Error ? e.message : "Balances unavailable."); } finally { setBusy(false); } }, [api, date, direction]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function save(e: FormEvent) { e.preventDefault(); const source = invoices.find(i => i.name === invoice); if (!source) return; setBusy(true); setError(""); setNotice(""); requestId.current ||= crypto.randomUUID(); try { const result = await api<BusinessRecord>({}, { action: "create_payment", direction, invoice, account, amount, reference_no: reference, reference_date: referenceDate, expected_modified: source.modified, request_id: requestId.current }); setNotice(`${result.name} saved as a draft. Refresh Payment Entry below, open the draft, then submit after review.`); requestId.current = ""; } catch (e) { setError(e instanceof Error ? e.message : "Payment unavailable."); } finally { setBusy(false); } }
  return <><div className="flex items-end gap-3"><label className="text-sm">Ledger balances as of<input className={input} type="date" value={date} onChange={e => setDate(e.target.value)} /></label><button className={button} disabled={busy} onClick={() => void load()}>Refresh balances</button></div><p className="my-3 text-sm text-[#716b66]">Balances come from posted ERPNext entries. Bank feeds and transfers require a separate banking integration.</p><div className="my-4 grid gap-3 sm:grid-cols-3">{banks.map(bank => <div key={bank.name} className="rounded-xl bg-[#f7f3ed] p-4"><p className="text-sm">{bank.account_name}</p><strong className="text-xl">{money(bank.balance, bank.account_currency)}</strong><p className="text-xs">{bank.account_type}</p></div>)}</div>{!busy && !banks.length && <p>No bank or cash ledger accounts configured.</p>}
    <h3 className="my-4 font-semibold">Record an invoice payment</h3><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Direction<select className={input} value={direction} disabled={busy} onChange={e => { setDirection(e.target.value); requestId.current = ""; }}><option value="Receive">Customer receipt</option><option value="Pay">Supplier payment</option></select></label><label className="text-sm">Outstanding invoice<select required className={input} value={invoice} onChange={e => { setInvoice(e.target.value); setAmount(invoices.find(i => i.name === e.target.value)?.outstanding_amount || 0); requestId.current = ""; }}><option value="">Choose invoice</option>{invoices.map(i => <option key={i.name} value={i.name}>{i.name} · {i.customer_name || i.supplier_name} · {money(i.outstanding_amount, i.currency)}</option>)}</select></label><label className="text-sm">Bank / cash / card ledger account<select className={input} value={account} required onChange={e => { setAccount(e.target.value); requestId.current = ""; }}><option value="">Choose account</option>{banks.map(b => <option key={b.name} value={b.name}>{b.account_name}</option>)}</select></label><label className="text-sm">Amount in invoice currency<input className={input} type="number" min="0.01" step="0.01" value={amount || ""} required onChange={e => { setAmount(Number(e.target.value)); requestId.current = ""; }} /></label><label className="text-sm">Bank transaction reference<input className={input} required={banks.find(b => b.name === account)?.account_type === "Bank"} maxLength={140} value={reference} onChange={e => { setReference(e.target.value); requestId.current = ""; }} /></label><label className="text-sm">Reference date<input type="date" required className={input} value={referenceDate} onChange={e => { setReferenceDate(e.target.value); requestId.current = ""; }} /></label><button className={primary} disabled={busy || !invoices.length}>Create payment draft</button></form>{error && <p role="alert" className="mt-3 text-red-800">{error}</p>}{notice && <p role="status" className="mt-3 text-green-900">{notice}</p>}
  </>;
}
function CreditNote({ api }: { api: Api }) {
  const [name, setName] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false); const requestId = useRef("");
  async function create(e: FormEvent) { e.preventDefault(); if (!window.confirm(`Create a full credit note draft for ${name}? Review it in Operations → Invoices before submitting.`)) return; setBusy(true); setError(""); setNotice(""); requestId.current ||= crypto.randomUUID(); try { const source = await api<BusinessRecord>({ action: "record", kind: "sales_invoices", name }); const result = await api<{ name: string }>({}, { action: "credit_note", invoice: name, expected_modified: source.modified, request_id: requestId.current }); setNotice(`${result.name} created. Review the draft in Operations → Invoices.`); } catch (e) { setError(e instanceof Error ? e.message : "Credit note unavailable."); } finally { setBusy(false); } }
  return <form onSubmit={create} className="rounded-xl bg-[#f7f3ed] p-4"><h3 className="mb-3 font-semibold">Sales credit note</h3><label className="text-sm">Submitted sales invoice number<input className={input} required value={name} onChange={e => { setName(e.target.value); requestId.current = ""; }} /></label><button className={`${button} mt-3`} disabled={busy}>Create full credit note draft</button>{error && <p role="alert" className="mt-3 text-red-800">{error}</p>}{notice && <p role="status" className="mt-3">{notice}</p>}</form>;
}

function Documents({ api, caps, onChanged, supabase }: { api: Api; caps: Capabilities; onChanged: () => Promise<void>; supabase: ReturnType<typeof createSupabaseBrowserClient> }) {
  const [letterTo, setLetterTo] = useState(""), [letterSubject, setLetterSubject] = useState(""), [letterBody, setLetterBody] = useState("");
  const [profile, setProfile] = useState(caps.profile), [kind, setKind] = useState("invoice"), [name, setName] = useState(""), [recipient, setRecipient] = useState(""), [subject, setSubject] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""); const requestId = useRef("");
  async function act(work: () => Promise<void>) { setBusy(true); setError(""); setNotice(""); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : "Document action unavailable."); } finally { setBusy(false); } }
  async function download() { await act(async () => { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch(`/api/proxc-management/business?${new URLSearchParams({ action: "document_pdf", kind, name })}`, { headers: { Authorization: `Bearer ${session?.access_token}` } }); if (!response.ok) throw new Error((await response.json() as { error: string }).error); const url = URL.createObjectURL(await response.blob()); const a = document.createElement("a"); a.href = url; a.download = `${name.replace(/[^a-zA-Z0-9_.-]/g, "_")}.pdf`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice("PDF downloaded with the Giftique letterhead."); }); }
  const keys = ["display_name", "address", "email", "phone_no", "website", "tax_id"] as const;
  return <><h3 className="font-semibold">Company details & letterhead</h3><p className="mb-4 mt-2 text-sm">These details appear on Giftique documents. Enter the company’s real address and TRN where applicable.</p><form onSubmit={e => { e.preventDefault(); void act(async () => { const result = await api<Capabilities["profile"]>({}, { action: "save_profile", data: Object.fromEntries(keys.map(key => [key, profile[key]])), expected_modified: profile.modified }); setProfile(result); await onChanged(); setNotice("Company details and letterhead saved."); }); }}><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2">{keys.map(key => <label key={key} className="text-sm capitalize">{key === "tax_id" ? "Tax registration number (TRN)" : key.replaceAll("_", " ")}<input className={input} type={key === "email" ? "email" : "text"} value={profile[key]} onChange={e => setProfile(p => ({ ...p, [key]: e.target.value }))} /></label>)}<button className={primary}>Save company & letterhead</button></fieldset></form>
    <label className="my-5 block text-sm">Company logo (PNG/JPEG, up to 3 MB)<input className={`${input} mt-1`} type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void act(async () => { if (file.size > 3000000) throw new Error("Choose a logo smaller than 3 MB."); const content = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = reject; reader.readAsDataURL(file); }); await api({}, { action: "upload_logo", content }); const updated = await api<Capabilities>({ action: "capabilities" }); setProfile(updated.profile); await onChanged(); setNotice("Logo saved to the letterhead."); }); }} /></label>
    <form className="my-7 border-t border-[#e5dfd8] pt-6" onSubmit={e => { e.preventDefault(); void act(async () => { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch("/api/proxc-management/business", { method: "POST", headers: { Authorization: `Bearer ${session?.access_token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "letter_pdf", recipient: letterTo, subject: letterSubject, message: letterBody, date: today() }) }); if (!response.ok) throw new Error((await response.json() as { error: string }).error); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = "Giftique-letter.pdf"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice("Company letter downloaded."); }); }}><h3 className="mb-4 font-semibold">Write a company letter</h3><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Recipient / address<textarea className={input} maxLength={2000} value={letterTo} onChange={e => setLetterTo(e.target.value)} /></label><label className="text-sm">Letter subject<input className={input} required maxLength={200} value={letterSubject} onChange={e => setLetterSubject(e.target.value)} /></label><label className="col-span-full text-sm">Letter text<textarea rows={6} className={input} required maxLength={10000} value={letterBody} onChange={e => setLetterBody(e.target.value)} /></label><button className={primary}>Download company letter PDF</button></fieldset><p className="mt-2 text-xs text-[#716b66]">Downloads a letter using your saved company details. Letter text is not stored.</p></form>
    <div className="mt-7 border-t border-[#e5dfd8] pt-6"><h3 className="font-semibold">Print & email documents</h3><p className="mb-4 mt-2 text-sm">{caps.email_ready ? `Outgoing sender: ${caps.sender}. Emails are queued through ERPNext.` : "Outgoing email is not configured. PDFs are available; connect your business sender account before sending email."}</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Document type<select className={input} value={kind} onChange={e => { setKind(e.target.value); requestId.current = ""; }}>{Object.entries({ invoice: "Sales invoice / credit note", order: "Sales order", delivery: "Delivery note", salary_slip: "Salary slip", purchase_invoice: "Purchase invoice" }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">Document number<input className={input} value={name} onChange={e => { setName(e.target.value); requestId.current = ""; }} /></label></div><button type="button" className={`${button} my-4`} disabled={busy || !name} onClick={() => void download()}>Download branded PDF</button>
    <form onSubmit={e => { e.preventDefault(); if (!window.confirm(`Email ${name} to ${recipient}?`)) return; void act(async () => { requestId.current ||= crypto.randomUUID(); await api({}, { action: "email_document", kind, name, recipient, subject, message, request_id: requestId.current }); setNotice("Email queued. Delivery depends on your configured email provider."); }); }}><fieldset disabled={busy || !caps.email_ready} className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Recipient<input className={input} type="email" required value={recipient} onChange={e => { setRecipient(e.target.value); requestId.current = ""; }} /></label><label className="text-sm">Subject<input className={input} required maxLength={200} value={subject} onChange={e => { setSubject(e.target.value); requestId.current = ""; }} /></label><label className="col-span-full text-sm">Message<textarea className={input} maxLength={10000} value={message} onChange={e => { setMessage(e.target.value); requestId.current = ""; }} /></label><button className={primary} disabled={!name}>Email document</button></fieldset></form></div>
    {error && <p role="alert" className="mt-4 text-red-800">{error}</p>}{notice && <p role="status" className="mt-4 text-green-900">{notice}</p>}
  </>;
}
